services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_db'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tech_inventory_db
    ports:
      - '5555:5432'